macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  only_if: $CIRRUS_BRANCH == 'master'
  name: Dev release (macos-aarch64)
  env:
    GRAALVM_VERSION: "21"
    GRAALVM_HOME: ${HOME}/graalvm/Contents/Home
    CLOJURE_LSP_PLATFORM: macos # used in release script
    CLOJURE_LSP_ARCH: aarch64
    CLOJURE_LSP_XMX: "-J-Xmx6g"
    GITHUB_TOKEN: ENCRYPTED[26786ca53221eb81db22b2ed4ebfde12d3765204867931bfad580dd31a0d677fce9df4da487c5b6969ac3397af638c7e]
  script: |
    sudo scripts/install-clojure /usr/local
    sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

    GRAALVM_FILENAME="graalvm-jdk-${GRAALVM_VERSION}_${CLOJURE_LSP_PLATFORM}-${CLOJURE_LSP_ARCH}_bin.tar.gz"
    DOWNLOAD_URL="https://download.oracle.com/graalvm/${GRAALVM_VERSION}/archive/${GRAALVM_FILENAME}"

    pushd ~
    if ! [ -d graalvm ]; then
      curl -O -sL $DOWNLOAD_URL
      mkdir graalvm
      tar xzf "$GRAALVM_FILENAME" -C graalvm --strip-components 1
    fi
    popd

    export PATH=$GRAALVM_HOME/bin:$PATH

    gu install native-image || true

    VERSION=$(date -u +"%Y.%m.%d-%H.%M.%S")
    echo "$VERSION-nightly" > lib/resources/CLOJURE_LSP_VERSION

    bb native-cli

    arch=$CLOJURE_LSP_ARCH
    archive="clojure-lsp-native-macos-$arch.zip"
    zip "$archive" clojure-lsp

    bb release-artifact "$archive" || true
  binaries_artifacts:
    path: "clojure-lsp-*.zip"
