#!/usr/bin/env bash

set -ev

VERSION=$"$(date -u +"%Y.%m.%d-%H.%M.%S")"

git fetch origin
git pull origin HEAD
echo "$VERSION" > resources/CLOJURE_LSP_VERSION
sed -i "s/## Unreleased/## Unreleased\n\n## $VERSION/g" CHANGELOG.md
git add resources/CLOJURE_LSP_VERSION
git commit -m "Release: $VERSION"
git tag "$VERSION"
git push origin HEAD
git push origin HEAD --tags
